config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :posts do
    resources :comments
  end

  get '/mypage', to: 'welcome#mypage'

  get '/users', to: 'users#users'

  get '/user/:id', to: 'users#show'

  get '/follow/:user_id', to: 'users#follow'

  post '/comment', to: 'comments#create'

  post '/like/:post_id', to: 'posts#like'

  delete '/dislike/:post_id', to: 'posts#dislike'

  delete '/unfollow/:user_id', to: 'users#unfollow'

  delete '/delcomment/:id', to: 'comments#destroy'

  delete '/pic_delete/:id', to: 'posts#pic_delete'

  get '/feed', to: 'welcome#feed'

  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

  validates :comment, presence: true,
                      length: { minimum: 5, maximum: 100 }

  validates :author, presence: true
end

app/models/follower.rb
class Follower < ApplicationRecord
  belongs_to :follower, class_name: 'User', foreign_key: 'follower'
  belongs_to :followed_user, class_name: 'User', foreign_key: 'followed_user'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true,
                    length: { maximum: 100, minimum: 5 }
  validates :author, presence: true
  has_one_attached :pic
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :user, optional: true, foreign_key: :author
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :avatar
  has_many :posts, foreign_key: :author
  has_many :likes

  has_many :follower_follows, foreign_key: :follower, class_name: 'Follower'
  has_many :followings, through: :follower_follows, source: :followed_user

  has_many :following_follows, foreign_key: :followed_user, class_name: 'Follower'
  has_many :followers, through: :following_follows, source: :follower
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[email avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[email avatar])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @comment = Comment.new
    @comment.comment = params[:comment]
    @comment.author = current_user.email
    @comment.post_id = params[:post_id]
    @comment.save!
    redirect_back fallback_location: '/'
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.author == current_user.email
      @comment.destroy
      redirect_back fallback_location: '/'
    else
      render plain: 'Error!'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user.id
    if @post.save
      redirect_to controller: 'welcome', action: 'mypage'
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.author == current_user.id
      if @post.update(post_params)
        redirect_to controller: 'welcome', action: 'mypage'
      else
        render 'edit'
      end
    else
      render plain: 'error!'
    end
  end
  
  def pic_delete
    @post = Post.find(params[:id])
    @post.pic.purge
    redirect_to action: "edit"
  end
  
  def destroy
    @post = Post.find(params[:id])
    if @post.author == current_user.id
      @post.destroy
      redirect_back fallback_location: '/'
    else
      render plain: 'error!'
    end
  end

  def like
    @like = Like.new
    @like.post_id = params[:post_id]
    @like.user_id = current_user.id
    redirect_back fallback_location: '/' if @like.save
  end

  def dislike
    Like.delete_by(post_id: params[:post_id], user_id: current_user.id)
    redirect_back fallback_location: '/'
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :pic)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def users
    @users = User.all.reject { |x| x == current_user }
    render 'users/users'
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(created_at: :desc)
    render 'users/showuser'
  end

  def follow
    @user = User.find(params[:user_id])
    if @user.followers.include?(current_user.id)
      redirect_to action: 'users'
    else
      @fol = Follower.new
      @fol.followed_user = User.find(params[:user_id])
      @fol.follower = current_user
      @fol.save!
      redirect_to action: 'users'
    end
   end

  def unfollow
    Follower.find_by_sql("DELETE FROM followers WHERE followed_user = '#{params[:user_id]}'   AND follower = '#{current_user.id}' ")
    redirect_back fallback_location: '/'
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    render 'welcome/welcome'
  end

  def mypage
    @posts = current_user.posts.order(created_at: :desc)
    @followers = current_user.followings
  end

  def feed
    @posts = Post.where(author: current_user.followings.pluck(:id)).order(created_at: :desc)
    render 'welcome/feed'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/start_helper.rb
module StartHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="main">
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Edit new post</h1>

<%= form_with( model: @post , local: true )  do |f| %>
<% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <br>
   <%= f.label 'title'%>
  <%= f.text_field(:title) %>
  <br>
  <%= f.label 'text'%>
  <%= f.text_area(:content, size: "50x10")%>
  <br>
  <%= f.label 'add photo'%>
  <%= f.file_field(:pic) %><br>
  <br>
  <%= link_to 'delete photo', "/pic_delete/#{@post.id}", method: :delete, class: "btn btn-outline-secondary btn-sm" %>
  <br>
  <%= f.submit "Save" %>
<%end%>

<%= @post.id %>

app/views/posts/new.html.erb
<h1>Create new post</h1>

<%= form_with( url: posts_path, local: true )  do |f| %>
 <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <br>
   <%= f.label 'title'%>
  <%= f.text_field(:title) %>
  <br>
  <%= f.label 'text'%>
  <%= f.text_area(:content, size: "50x10")%>
  <br>
  <%= f.label 'add photo'%>
  <%= f.file_field(:pic) %>
  <br>
  <%= f.submit "Add post" %>
<%end%>

app/views/posts/show.html.erb
<%= @post.title %>

app/views/users/showuser.html.erb
<h3> <%= @user.email %></h3>
<br>
<% if @user.avatar.attached? %>

<%= image_tag(@user.avatar, size: "150x150") %>

<% end %>
<br>
<%= link_to 'Main page', '/', class: "btn btn-outline-primary"%>
<hr>


<% @posts.each do |post| %>
   <h4> <%= post.title %> </h4> <br>
    <%= post.content %><br>
    <%= post.created_at %><br>
  <% if post.pic.attached? %>
    <%= image_tag(post.pic, size: "500x300") %>
  <% end %>

 <div>

 <p>Likes : <%= post.likes.size %> </p>
 
        <% if post.likes.pluck(:user_id).include?(current_user.id) %>
            <%= 'Liked' %>
            <%= link_to 'dislike', "/dislike/#{post.id}", method: :delete, class: "btn btn-outline-secondary" %>
            <% else %>
              <%= link_to 'like', "/like/#{post.id}", method: :post, class: "btn btn-outline-success" %>
        <% end %>
 
 </div>
  <h3>Comments: </h3>
  <% comments = post.comments%>
  <% comments.each do |c|%>
  <%= c.author %>:
  <%= c.comment %><br>
  <% if c.author == current_user.email %>
    <%= link_to 'Delete comment', "/delcomment/#{c.id}", method: :delete, class: "btn btn-sm btn-outline-primary" %><br>
  <% end %>
  
  <%end%>
  <h4>Add your comment:</h4>
<%= form_with(model: @post, url: '/comment', method: :post,  local: true) do |form| %>
    <%= form.label :comment %><br>
    <%= form.text_area :comment %>
    <%= form.hidden_field :post_id, value: post.id %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>
 
    <hr>
<% end %>

app/views/users/users.html.erb
<div style="text-align: center;">
<%= link_to 'Main page', '/', class: "btn btn-outline-primary" %>
</div>
<br>
<hr>
<% @users.each do |user| %>
  <% if user.avatar.attached? %>
    <%= image_tag(user.avatar, size: "100x100") %>
    <% else %>
    <%= image_tag "img.jpg", size: "100x100" %>
  <% end %>
    <%= link_to "#{user.email}" , "user/#{user.id}", class: "btn btn-outline-info" %>
    <br>
    
    
    <% if user.followers.include?(current_user) %>
      <%= link_to 'Unfollow', "unfollow/#{user.id}", method: :delete, class: "btn btn-sm btn-outline-danger" %>
      <% else %>
      <%= link_to 'follow', "follow/#{user.id}", class: "btn btn-sm btn-outline-primary" %>
    <% end %>
    


    <hr>
<% end %>

app/views/welcome/feed.html.erb
<div id="posts" class="container">
  <h2 style="text-align: center;">Feed <br>
  <%= link_to 'Main', '/' %>
  </h2>

<hr>
<% @posts.each do |post| %>
<h4><%= link_to "#{User.find(post.author).email}", "/user/#{post.author}"%></h4> <br>
<h4><%= post.title %></h4> <br>
<%= post.content %> <br>

  <% if post.pic.attached? %>
    <%= image_tag(post.pic, size: "500x300") %>
  <% end %>
  <p>Likes: <%= post.likes.size %> </p> 
  <% like = Like.where('post_id = ?', post.id) %>

        
        <% if post.likes.pluck(:user_id).include?(current_user.id) %>
            <%= 'Liked' %>
            <%= link_to 'dislike', "/dislike/#{post.id}", method: :delete, class: "btn btn-outline-secondary" %>
            <% else %>
              <%= link_to 'like', "/like/#{post.id}", method: :post, class: "btn btn-outline-success" %>
        <% end %>

<br>
<%= 'Comments: '%>
<br>
<% comments = post.comments %>
  <% comments.each do |c| %>
    <%= c.author %>:
    <%= c.comment %>
    <br>
    <% if c.author == current_user.email %>
    <%= link_to 'Delete comment', "/delcomment/#{c.id}", method: :delete, class: "btn btn-sm btn-outline-primary" %><br>
  <% end %>
  <% end %>
<hr>
<% end %>
</div>

app/views/welcome/mypage.html.erb
<div id="mypage">

<div id="userinfo">
<% if user_signed_in? %>
<h3> <%= current_user.email %></h3>
<br>
<% if current_user.avatar.attached? %>

<%= image_tag(current_user.avatar, size: "150x150") %>

<% else %>
<%= image_tag('img.jpg', size: "150x150") %>
<% end %>
</div>

<div id="follows">
<h4>Followings</h4>
<% @followers.each do |f| %>
  <%= link_to "#{f.email}", "user/#{f.id}", class: "btn btn-outline-success"  %>
  <%= link_to 'unfollow', "/unfollow/#{f.id}", method: :delete %>
    <br>
<% end %>

<% end %>
</div>

<div id="newpost">
<%= link_to 'Add new post', '/posts/new', class: "btn btn-outline-primary"%>
<br>
<br>
<%= link_to 'Edit account', edit_user_registration_path, class: "btn btn-outline-primary" %>
<br>
<br>
<%= link_to 'Feed', '/feed', class: "btn btn-outline-primary" %>
<br>
<br>
<%= link_to 'To main page', '/', class: "btn btn-outline-primary"%>
</div>

<div id="editpage">
  
</div>

<hr>

<div id="posts" class="container">
  <h2 style="text-align: center;">My posts:</h2>
<hr>
<% @posts.each do |post| %>

<h4><%= post.title %></h4> <br>
<%= post.content %> <br>

  <% if post.pic.attached? %>
    <%= image_tag(post.pic, size: "500x300") %>
  <% end %>
  <p>Likes: <%= post.likes.size %> </p> 
  
  <%= link_to 'Edit post', edit_post_path(post), class: "btn btn-sm btn-outline-primary" %>
  <%= link_to 'delete post', post_path(post), method: :delete, class: "btn btn-sm btn-outline-danger", data:{ confirm: "are you sure?"} %>

<br>
<%= 'Comments: '%>
<br>
<% comments = post.comments %>
  <% comments.each do |c| %>
    <%= c.author %>:
    <%= c.comment %>
    <br>
  <% end %>
<hr>
<% end %>
</div>


</div>

app/views/welcome/userpage.html.erb
<% if user_signed_in? %>

<%= current_user.email %>
	
<% if current_user.avatar.attached? %>

<%= image_tag(current_user.avatar, size: "300x300") %>

<% end %>

<div>
<h4>Users i follow</h4>
</div>

<% @followers.each do |f| %>
  <%= f.email %>
  <%= link_to 'user', "user/#{f.id}" %>
  <%= link_to 'unfollow', "/unfollow/#{f.id}", method: :delete %>
    <br>
<% end %>
<hr>


<%= form_with(model: @post, url: posts_path, local: true ) do |f| %>
   <%= f.label 'title'%>
  <%= f.text_field (:title) %>
  <br>
  <%= f.label 'text'%>
  <%= f.text_field (:content)%>
  <br>
  <%= f.label 'add photo'%>
  <%= f.file_field (:pic) %>
  <br>
  <%= f.submit "Add post" %>
<%end%>


<% end %>
<hr>
<% @posts.each do |post| %>

<%= post.title %> <br>

  <% if post.pic.attached? %>
    <%= image_tag(post.pic, size: "500x300") %>
  <% end %>
<br>
<% comments = post.comments %>
  <% comments.each do |c| %>
    <%= c.author %>:
    <%= c.comment %>
    <br>
  <% end %>
<hr>
<% end %>

app/views/welcome/welcome.html.erb
<div class="main">
	<h1>Welcome to Rails App</h1>

<% if user_signed_in? %>

	<%= current_user.email %>
	<br>
	<% if current_user.avatar.attached? %>

<%= image_tag(current_user.avatar, size: "100x100") %>

<% end %>
	<br>
	<%= link_to 'My page', '/mypage'%>
	<%= link_to 'All users', 'users'%>
	<%= link_to 'Edit page', edit_user_registration_path %>
	<%= link_to 'Logout', destroy_user_session_path , method: :delete %>
	<% else %>

	<%= link_to 'Registration', new_user_registration_path %>

	<%= link_to 'Login', new_user_session_path %>

	<% end %>
</div>